### PR TITLE
#284 - cache impl to load from remote

### LINKED ISSUE #284: `Cache` implementation
Let's add implementation of `Cache` to always load content from remote and cache it to storage. Content should be obtained from storage cache only if remote failed to return item.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #284 
Added implementation of `Cache` to always load content from remote and add to storage and get from cache only if remote failed to return content.

### CODE REVIEW

File: src/main/java/com/artipie/asto/AsyncContent.java [hunk 1]
```diff
@@ -43,4 +43,31 @@
 
     @Override
     CompletionStage<? extends Content> get();
+
+    /**
+     * Failed async content.
+     * @since 0.3
```
Comment (olegmoz) [inline src/main/java/com/artipie/asto/AsyncContent.java:49]: @olenagerasimova `@since` version is off, it should be `0.30`. Same in other classes added in this PR

File: src/main/java/com/artipie/asto/cache/FromStorageCache.java [hunk 2]
```diff
@@ -33,10 +33,12 @@
 import java.util.concurrent.CompletionStage;
 
 /**
- * Storage cache implementation.
+ * Cache implementation that trays to obtain items from storage cache,
```
Comment (olegmoz) [inline src/main/java/com/artipie/asto/cache/FromStorageCache.java:36]: @olenagerasimova there is typo, "trays" instead of "tries"

**Review by olegmoz — CHANGES_REQUESTED** [review]
@olenagerasimova thanks, please see two minor comments

**Comment by olenagerasimova** [comment]
@olegmoz thanks, corrected

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/asto#285` is not assigned, can't get performer
