### PR TITLE
#217 - Fix size of the content

### LINKED ISSUE #217: `FileStorage` returns content without unknown size
`FileStorage` returns content without size specified. This was not the case some time ago and in my opinion all `Storage` implementations should return `Content` with known size

### PR DESCRIPTION
**Pull request by genryxy**
Closes #217 
Add size to the constructor of `FileStorage`.

### CODE REVIEW

**Comment by 0crat** [comment]
@genryxy[/z](https://www.0crat.com/u/genryxy) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thanks, the fix looks good. Please add a test to ensure that fix works and to avoid repeating the problem in future

**Comment by genryxy** [comment]
@olegmoz thanks, added test

File: src/test/java/com/artipie/asto/FileStorageTest.java [hunk 1]
```diff
@@ -167,6 +167,20 @@ void saveAndLoadHugeFiles(@TempDir final Path tmp) throws Exception {
...
+        this.storage.save(
+            key,
+            new Content.OneTime(new Content.From(content))
+        ).get();
+        MatcherAssert.assertThat(
+            this.storage.value(key).get().size().get(),
+            new IsEqual<>((long) content.length)
+        );
+    }
+
```
Comment (olegmoz) [inline src/test/java/com/artipie/asto/FileStorageTest.java:183]: @genryxy this test could be done for all `Storage` and in my opinion it will be right to do so. Please move it to `StorageSaveAndLoadTest` so we will ensure that all `Storage` implementation return `Content` with size

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thanks, please see one comment

**Comment by genryxy** [comment]
@olegmoz moved test to `StorageSaveAndLoadTest`

**Review by olegmoz — APPROVED** [review]
@genryxy thanks, approved

**Comment by 0crat** [comment]
Job `gh:artipie/asto#238` is not assigned, can't get performer
