### PR TITLE
fix: prevent file to be written out of FileStorage scope

### LINKED ISSUE #332: Prevent arbitrary file write in `FileStorage`
We should not allow to escape the sandbox of `FileStorage` and `SubStorage`, e.g. if we use `/var/artipie` as a primary storage and somebody is trying to write the key `/../../etc/passwd` the `FilesStorage` should throw and exception. Generally, the `Key` may not contain any up command and normalized path from `Key` should be always point to some sub-element.

Similar issue in RPM: https://github.com/artipie/rpm-adapter/pull/437/

### PR DESCRIPTION
**Pull request by baudoliver7**
Closes #332

Throw an exception when attempting to write out of `FileStorage` scope

### CODE REVIEW

**Comment by baudoliver7** [comment]
@artipie/maintainers ready to be reviewed :)

File: src/main/java/com/artipie/asto/fs/FileStorage.java [hunk 1]
```diff
@@ -125,6 +125,10 @@ public FileStorage(final Path path) {
 
     @Override
     public CompletableFuture<Void> save(final Key key, final Content content) {
+        final Path next = this.dir.resolve(key.string());
+        if (!next.normalize().startsWith(next)) {
+            throw new IllegalStateException("Entry path is out of storage.");
+        }
```
Comment (genryxy) [inline src/main/java/com/artipie/asto/fs/FileStorage.java:131]: I'd suggest to wrap this exception in `ArtipieException` or just throw `ArtipieException`

**Review by genryxy — CHANGES_REQUESTED** [review]
@baudoliver7 thanks, one suggestion

File: src/main/java/com/artipie/asto/fs/FileStorage.java (hunk 1 above)
Comment (baudoliver7) [reply src/main/java/com/artipie/asto/fs/FileStorage.java:131]: @genryxy Ok, in this cas let throw `ArtipieException`

**Review by genryxy — APPROVED** [review]
@baudoliver7 thanks, looks good to me
@g4s8 please take a look

File: src/main/java/com/artipie/asto/fs/FileStorage.java [hunk 2]
```diff
@@ -125,6 +125,10 @@ public FileStorage(final Path path) {
 
     @Override
     public CompletableFuture<Void> save(final Key key, final Content content) {
+        final Path next = this.dir.resolve(key.string());
+        if (!next.normalize().startsWith(next)) {
+            throw new ArtipieException("Entry path is out of storage.");
```
Comment (g4s8) [inline src/main/java/com/artipie/asto/fs/FileStorage.java:130]: This exception should be put as the result of `CompletableFuture`, you can use helper object for Java-1.8 [FailedCompletionStage](https://github.com/artipie/asto/blob/master/src/main/java/com/artipie/asto/FailedCompletionStage.java):
```java
return new FailedCompletionStage<>(new ArtipieException("Entry path is out of storage.")).toCompletableFuture();
```

Also, I'd suggest using [ArtipieIOException](https://github.com/artipie/asto/blob/master/src/main/java/com/artipie/asto/ArtipieIOException.java) here (since it's IO operation error).

**Review by g4s8 — CHANGES_REQUESTED** [review]
@baudoliver7 thanks, please check my comment regarding code. Another comment is that `save` is not the only write operation, we also have `delete` and `move` operations which can write data to storage, so these two operations also need the same path check.

File: src/main/java/com/artipie/asto/fs/FileStorage.java (hunk 2 above)
Comment (baudoliver7) [reply src/main/java/com/artipie/asto/fs/FileStorage.java]: @g4s8 got it

**Comment by baudoliver7** [comment]
> @baudoliver7 thanks, please check my comment regarding code. Another comment is that `save` is not the only write operation, we also have `delete` and `move` operations which can write data to storage, so these two operations also need the same path check.

@g4s8 You are right. `delete` and `move` are another way to write write storage.

**Comment by baudoliver7** [comment]
@g4s8 please, could you review the new changes ?

**Comment by baudoliver7** [comment]
@g4s8 ping

**Comment by baudoliver7** [comment]
@g4s8 how about my last changes ?

**Comment by baudoliver7** [comment]
@g4s8 ping

**Comment by baudoliver7** [comment]
@g4s8 Almost a week to wait a check/merge !

**Review by g4s8 — APPROVED** [review]
@baudoliver7 thanks
