### PR TITLE
fix: fix CI to run tests of EtcdStorageITCase

### LINKED ISSUE #309: The test is disabled, the CI can't start ETCD extension which depends on testcontainer with etcd...
The puzzle `306-ccf10929` from #306 has to be resolved: 

https://github.com/artipie/asto/blob/fc2ec934d3028b695a17e487f4a368fa425bac06/src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java#L46-L48

The puzzle was created by @g4s8 on 21-Apr-21. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by baudoliver7**
Closes #309

- Fix some `EtcdStorage` methods to pass failed tests
- Introduce `EtcdMeta`, metadata class for `EtcdStorage`
- Enable `EtcdStorageITCase` and pull automatically `Etcd` docker image before all tests
- Add a todo to support integration tests based on `testcontainers` for `Windows` (it works well with `Linux`)

### CODE REVIEW

**Comment by baudoliver7** [comment]
@artipie/maintainers ready to be reviewed :)

File: src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java [hunk 1]
```diff
@@ -5,54 +5,105 @@
...
     @BeforeEach
     void setUp() {
         this.storage = new EtcdStorage(
             Client.builder().endpoints(ETCD.getClientEndpoints()).build()
         );
     }
 
+    @AfterAll
+    static void afterAll() {
+        ETCD.close();
```
Comment (g4s8) [inline src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java:75]: @baudoliver7 we also need to stop docker conteiber here if we start it in beforeall method

File: src/main/java/com/artipie/asto/etcd/EtcdStorage.java [hunk 2]
```diff
@@ -67,13 +71,28 @@ public EtcdStorage(final Client client) {
...
-        return this.client.getKVClient().get(
-            keyToSeq(prefix),
-            GetOption.newBuilder()
-                .withKeysOnly(true)
-                .withSortOrder(SortOrder.ASCEND)
-                .build()
-        ).thenApply(
+        final CompletableFuture<GetResponse> future;
+        if (prefix == Key.ROOT) {
+            final ByteSequence root = keyToSeq(new Key.From("\0"));
```
Comment (g4s8) [inline src/main/java/com/artipie/asto/etcd/EtcdStorage.java:76]: There's no need to wrap a key here - we can just create private constant of byteSequence

File: src/main/java/com/artipie/asto/etcd/EtcdStorage.java [hunk 3]
```diff
@@ -108,14 +127,22 @@ public EtcdStorage(final Client client) {
 
     @Override
     public CompletableFuture<? extends Meta> metadata(final Key key) {
-        return CompletableFuture.completedFuture(Meta.EMPTY);
+        return this.client.getKVClient().get(keyToSeq(key)).thenApply(
+            rsp -> rsp.getKvs().stream().max(
```
Comment (g4s8) [inline src/main/java/com/artipie/asto/etcd/EtcdStorage.java:131]: @baudoliver7 is it possible to fetch metadata without loading full content of key-values?

**Review by g4s8 — CHANGES_REQUESTED** [review]
@baudoliver7 please check my comments

File: src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java (hunk 1 above)
Comment (baudoliver7) [reply src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java:75]: @g4s8 This is exactly what we do with the instruction:
```java
ETCD.close();
```
This instruction close the cluster :
```java
public void close() {
    this.cluster.close();
}
```
And the cluster close all containers :
```java
public void close() {
    containers.forEach(EtcdContainer::close);
}
```
This is the code of method `EtcdContainer::close` :
```java
public void close() {
    if (this.container != null) {
        this.container.stop();
    }

    deleteDataDirectory(this.dataDirectory);
}
```

File: src/main/java/com/artipie/asto/etcd/EtcdStorage.java (hunk 3 above)
Comment (baudoliver7) [reply src/main/java/com/artipie/asto/etcd/EtcdStorage.java:131]: @g4s8 We can do that, but we will not have size of value. We can have other metadata. And unfortunately, there is no way to get size of value without the value itself. I checked in [etcd developer guide](https://etcd.io/docs/v3.5/dev-guide/interacting_v3/) and there is nothing there that mention that.

**Comment by baudoliver7** [comment]
@g4s8 please, could you check my comments and last changes ?

**Comment by baudoliver7** [comment]
@g4s8 need to complete this issue to tackle #310

**Comment by baudoliver7** [comment]
@g4s8 while waiting a review, let me add a workflow for integration tests in order to anticipate the task #310 :)

**Comment by baudoliver7** [comment]
@g4s8 all things are ok now for ci integration testing with `testcontainers` :)
please, review/merge

File: .github/workflows/integration-tests.yml [hunk 4]
```diff
@@ -0,0 +1,38 @@
+---
+name: Integation tests
```
Comment (g4s8) [inline .github/workflows/integration-tests.yml:2]: Why do we need separate workflow for tests? We already have integration tests enabled in primary workflow

**Review by g4s8 — CHANGES_REQUESTED** [review]
@baudoliver7 please check my comment

File: .github/workflows/integration-tests.yml (hunk 4 above)
Comment (baudoliver7) [reply .github/workflows/integration-tests.yml:2]: @g4s8 It's because it could take so much time to be executed 6 times

Comment (baudoliver7) [reply .github/workflows/integration-tests.yml:2]: For each of them, we have to pull docker image and run all integration tests

Comment (baudoliver7) [reply .github/workflows/integration-tests.yml:2]: So, by my configuration, I run only unit tests in primary workflow and integration tests in `integration-test.yml`

Comment (baudoliver7) [reply .github/workflows/integration-tests.yml:2]: You could check it in build logs.

Comment (baudoliver7) [reply .github/workflows/integration-tests.yml:2]: @g4s8 WDYT ?

Comment (baudoliver7) [reply .github/workflows/integration-tests.yml:2]: @g4s8 On reflection, I think I will use primary workflow to enable `testcontainers` for integration tests. It will allow us to test in several environments (OS and JDK).

Comment (g4s8) [reply .github/workflows/integration-tests.yml]: I don't think it's a good reasons for disabling it. GitHub pulls images quite fast. Please revert workflows back to check etcd rest cases in standard `verify` workflow

Comment (baudoliver7) [reply .github/workflows/integration-tests.yml]: @g4s8 I agree with you

**Comment by baudoliver7** [comment]
@g4s8 I use now the main workflow for integration tests. But I got on windows, an issue about integration tests based on testcontainers. All things work well on Ubuntu.

**Comment by baudoliver7** [comment]
@g4s8 good now to be reviewed :)

File: .github/workflows/maven.yml [hunk 5]
```diff
@@ -27,4 +27,20 @@ jobs:
...
-        run: mvn clean verify -B -Pqulice
+        run: |
+          if [ "$RUNNER_OS" == "Linux" ]; then
+             mvn clean verify -B -Pqulice
+          elif [ "$RUNNER_OS" == "Windows" ]; then
+               mvn clean test -B -Pqulice
+          else
+             echo "$RUNNER_OS not supported"
+             exit 1
+          fi
```
Comment (g4s8) [inline .github/workflows/maven.yml:38]: This should be done on test case level - no need to disable all tests for OS, just use `@DisabledOnOs` annotation for test case: https://junit.org/junit5/docs/5.3.0/api/org/junit/jupiter/api/condition/DisabledOnOs.html

File: .github/workflows/maven.yml [hunk 6]
```diff
@@ -27,4 +27,20 @@ jobs:
...
+        shell: bash
+  # @todo #309:30min Run Etcd in windows containers while testing on windows.
```
Comment (g4s8) [inline .github/workflows/maven.yml:40]: And this todo also is not for CI scripts, please fully revert workflow file and put all related changes to test case only

File: pom.xml [hunk 7]
```diff
@@ -241,19 +241,16 @@ SOFTWARE.
...
       </plugin>
       <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-failsafe-plugin</artifactId>
+        <version>3.0.0-M5</version>
         <configuration>
-          <parallel>none</parallel>
+          <forkCount>1</forkCount>
+          <reuseForks>true</reuseForks>
+          <useSystemClassLoader>false</useSystemClassLoader>
```
Comment (g4s8) [inline pom.xml:253]: Why do we need such a configuration here?

File: pom.xml [hunk 8]
```diff
@@ -241,19 +241,16 @@ SOFTWARE.
...
-            <artifactId>surefire-junit-platform</artifactId>
-            <version>2.22.2</version>
-          </dependency>
-        </dependencies>
+        <version>3.0.0-M5</version>
       </plugin>
       <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-failsafe-plugin</artifactId>
+        <version>3.0.0-M5</version>
```
Comment (g4s8) [inline pom.xml:249]: Same here - you can remove it, since it's defined in parent pom

**Review by g4s8 — CHANGES_REQUESTED** [review]
@baudoliver7 thanks, the test looks good; please check my comments about pom and workflows

File: .github/workflows/maven.yml (hunk 6 above)
Comment (baudoliver7) [reply .github/workflows/maven.yml:40]: @g4s8 done

File: pom.xml [hunk 9]
```diff
@@ -241,19 +241,16 @@ SOFTWARE.
...
         <artifactId>maven-surefire-plugin</artifactId>
-        <version>2.22.2</version>
-        <dependencies>
-          <dependency>
-            <groupId>org.apache.maven.surefire</groupId>
-            <artifactId>surefire-junit-platform</artifactId>
-            <version>2.22.2</version>
-          </dependency>
-        </dependencies>
+        <version>3.0.0-M5</version>
```
[the remark this answers is not in the document]
Comment (baudoliver7) [reply pom.xml:244]: Ok

File: pom.xml (hunk 8 above)
Comment (baudoliver7) [reply pom.xml:249]: I noticed that integration tests doesn't run with the version configured in parent pom (version `3.0.0-M4`). We got this :
```cmd
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.artipie.asto.etcd.EtcdStorageITCase
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.685 s - in com.artipie.asto.etcd.EtcdStorageITCase
```
Tests run when we use version `3.0.0-M5`.

File: pom.xml (hunk 7 above)
Comment (baudoliver7) [reply pom.xml:253]: It's to fix these warnings :
```cmd
[WARNING] useSystemClassLoader setting has no effect when not forking
[WARNING] The parameter forkCount should likely not be 0, not forking a JVM for tests reduce test accuracy, ensure to have a <forkCount> >= 1.
```

Comment (g4s8) [reply pom.xml]: You can submit an issue about these warnings here https://github.com/artipie/ppom/issues and we'll discuss how to solve it

File: pom.xml (hunk 8 above)
Comment (g4s8) [reply pom.xml:244]: I see, will fix it with parent pom update later

**Review by g4s8 — DISMISSED** [review]
@baudoliver7 thanks

File: pom.xml (hunk 7 above)
Comment (baudoliver7) [reply pom.xml]: Done here : https://github.com/artipie/ppom/issues/82

**Review by g4s8 — APPROVED** [review]
