### PR TITLE
#153 - Removed Single.blockingGet() calls

### LINKED ISSUE #153: InMemory value method not working
In npm adapter I tried to do following with in-memory storage:

```java
    @Test
    public final void uploadWorksProperly()
        throws IOException, InterruptedException, ExecutionException {
        final Vertx vertx = Vertx.vertx();
        final int port = this.randomPort();
        final Storage storage = new InMemoryStorage();
        final VertxSliceServer server = new VertxSliceServer(
            vertx,
            new NpmSlice(
                storage
            ),
            port
        );
        server.start();
        final WebClient web = WebClient.create(vertx);
        final int code = web.put(port, "localhost", "/package")
            .rxSendBuffer(Buffer.buffer(
                "{ \"versions\":  {\"1.0.1\": {}, \"1.0.4\": {}, \"1.0.2\": {}} }"
            ))
            .blockingGet()
            .statusCode();

        web.close();
        server.close();
        vertx.close();
        storage.value(new KeyFromPath("/package")).get();
    }
```

and last line with `storage.value(new KeyFromPath("/package")).get();` simply waits forever and never completes.

On the other hand `FileStorage` works fine.

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #153 
Reason for example code to fail is endless `Publisher`. It is getting read inside `synchronized`, so read operation cannot obtain the lock.
Fixed it by  bringing content reading outside of synchronized section + got rid of other Single.blockingGet() usage because it creates errors in Vert.x environment

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#154](https://github.com/artipie/asto/issues/154) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/abbe3f42-96a5-41c7-8f17-fd7cad2914c1); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

File: src/main/java/com/artipie/asto/memory/InMemoryStorage.java [hunk 1]
```diff
@@ -89,19 +90,17 @@ public InMemoryStorage() {
...
-            () -> {
-                synchronized (this.data) {
-                    this.data.put(
-                        key.string(),
-                        new Remaining(
-                            new Concatenation(content).single().blockingGet(),
-                            true
-                        ).bytes()
-                    );
+        return new Concatenation(content).single().to(SingleInterop.get())
```
Comment (Vatavuk) [inline src/main/java/com/artipie/asto/memory/InMemoryStorage.java:93]: @olegmoz can we add a test that will verify that the bug is fixed?

Comment (olegmoz) [reply src/main/java/com/artipie/asto/memory/InMemoryStorage.java:93]: @Vatavuk though about it, but not sure how to do it. The problem is we need to check that code is not getting stuck in synchronized section. But what if it still does? The unit test will never finish. Not sure that having such test is a nice idea

Comment (g4s8) [reply src/main/java/com/artipie/asto/memory/InMemoryStorage.java:93]: @olegmoz maybe you can use `@Timeout` junit annotation? It will fail the test if it can't pass within specified amount of time, e.g. this test will fail:
```java
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS)
void test() throws Exception {
    Thread.sleep(2000);
}
```
with error:
> java.util.concurrent.TimeoutException: test() timed out after 1 second

Comment (Vatavuk) [reply src/main/java/com/artipie/asto/memory/InMemoryStorage.java:93]: @olegmoz maybe we can run the test code in a separate thread and kill the thread if more than X seconds passed and fail the test. If it is too complex and you don't see an additional value that we would get from such a test than we can leave as is.

Comment (olegmoz) [reply src/main/java/com/artipie/asto/memory/InMemoryStorage.java:93]: @g4s8 @Vatavuk wqs pretty sure timeout feature was still missing in junit, thanks! Added the test, please review

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@Vatavuk please make sure you will find at least 3 issues during next CR, thanks

**Comment by Vatavuk** [comment]
@sereshqua ok

**Comment by sereshqua** [comment]
@0crat quality acceptable
