### PR TITLE
Fix RxFile#save and enhance RxFileTest#saveWorks with more iterations

### LINKED ISSUE #45: RxFile test sometimes fails
The test for `RxFile` sometimes fails:
```
Results :
Failed tests: 
  RxFileTest.rxFileSaveWorks:88 
Expected: "hello-world!!!"
     but: was "helor"
```
see https://github.com/artipie/asto/pull/44/checks?check_run_id=436298450

It's not stable bug, reproduced just once, but it looks critical if `RxFile` may not work correctly time to time.

### PR DESCRIPTION
**Pull request by Sammers21**
closes #45 

* RxFile#save test enhanced with more iterations
* Fix RxFile#save implementation
* Stream errors are propagated to the resulted completable

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#50](https://github.com/artipie/asto/issues/50) is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e45581b4-10bf-4220-9cf2-ba39bd0d7f76); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

File: src/test/java/com/artipie/asto/RxFileTest.java [hunk 1]
```diff
@@ -74,18 +74,20 @@ public void rxFileSaveWorks() throws IOException {
...
-                Flowable.fromArray(new ByteArray(hello.getBytes()).boxedBytes()).map(
-                    aByte -> {
-                        final byte[] bytes = new byte[1];
-                        bytes[0] = aByte;
-                        return ByteBuffer.wrap(bytes);
-                    }
-                )
-            ).blockingAwait();
-        MatcherAssert.assertThat(new String(Files.readAllBytes(temp)), Matchers.equalTo(hello));
+        for (int idx = 0; idx < 100; idx += 1) {
```
Comment (iakunin) [inline src/test/java/com/artipie/asto/RxFileTest.java]: @Sammers21 the build is failing now with the following error:
```
Failed tests: 
  RxFileTest.rxFileSaveWorks:89 
Expected: "hello-world!!!"
     but: was "helloworld!!!"
```

Link to build: https://github.com/artipie/asto/pull/50/checks?check_run_id=440602444

**Comment by Sammers21** [comment]
@iakunin ,  review the pull request please

**Comment by Sammers21** [comment]
@iakunin , review the pull request please

File: pom.xml [hunk 2]
```diff
@@ -25,7 +25,7 @@ SOFTWARE.
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <properties>
-    <rxjava.version>3.0.0-RC6</rxjava.version>
+    <vertx.version>4.0.0-SNAPSHOT</vertx.version>
```
Comment (g4s8) [inline pom.xml]: @Sammers21 let's use any constant snapshot version, e.g. `4.0.0-20200212.144500-295`

File: src/test/java/com/artipie/asto/RxFileTest.java [hunk 3]
```diff
@@ -66,18 +66,21 @@ public void rxFileSaveWorks() throws IOException {
...
-                    aByte -> {
-                        final byte[] bytes = new byte[1];
-                        bytes[0] = aByte;
-                        return ByteBuffer.wrap(bytes);
-                    }
-                )
-            ).blockingAwait();
-        MatcherAssert.assertThat(new String(Files.readAllBytes(temp)), Matchers.equalTo(hello));
+        final int iterations = 100;
+        for (int idx = 0; idx < iterations; idx += 1) {
```
Comment (g4s8) [inline src/test/java/com/artipie/asto/RxFileTest.java]: @Sammers21 maybe you can use `@RepeatedTest` [Junit annotation](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/RepeatedTest.html) instead of for loop here?

File: pom.xml (hunk 2 above)
Comment (Sammers21) [reply pom.xml]: This would not work because Vert.x is not a single artifact: we are using a few of them: `core`, `rx-java-2`, `parent`. All of them have different constants.

Comment (iakunin) [inline pom.xml]: @Sammers21 is it a really good decision to use snapshot version of `vertx`? Why we need exactly snapshot version?

Comment (Sammers21) [reply pom.xml]: This code :
```
asyncFile.toSubscriber()                            .onWriteStreamEnd(emitter::onComplete)                          .onWriteStreamError(emitter::onError)
```
Won't compile without it

Comment (iakunin) [reply pom.xml]: @Sammers21 got it, thanks.

Comment (g4s8) [reply pom.xml]: @Sammers21 then we can use constant snapshot version only for `vertx-core` explicitly (until any stable version will be published). The reasons why I don't like `4.0.0-SNAPSHOT` is: 1) we'll have different dependency code in local builds/tests; 2) dependency will be updated implicitly on each new `artipie/asto` release.

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

File: pom.xml (hunk 2 above)
Comment (Sammers21) [reply pom.xml]: @g4s8 , done

**Comment by paulodamaso** [comment]
@iakunin Is this PR good to merge? I have one review depending on it

**Comment by g4s8** [comment]
@rultor release, tag=`0.13.1`

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0crat** [comment]
Job audit: performer @iakunin[/z](https://www.0crat.com/u/iakunin)[/z](https://www.0crat.com/u/iakunin) didn't make CR comments

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
