### PR TITLE
Revert signature changes made with BlockingStorage

### LINKED ISSUE #281: Back to the old BlockingStorage
BlockingStorage was initially designed for simplicity, in #171 method signatures have been modified and now you need to explicitly handle the exceptions, which might look awful in a tiny lambda body.

Let's roll back the changes made.

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #281.

### CODE REVIEW

**Comment by olegmoz** [comment]
@Sammers21 please explain reason for these changes. I do not see how it is related to #171 and word "horrible" is not really informative

**Comment by Sammers21** [comment]
@olegmoz, #171 is the ticket number where the changes were introduced. Reverted with the same ticket number.

**Comment by Sammers21** [comment]
@olegmoz, description has been updated

**Comment by olegmoz** [comment]
> @Sammers21 please explain reason for these changes. I do not see how it is related to #171 and word "horrible" is not really informative

@Sammers21 it is sad that changes were made without proper explanation. Let's avoid this kind of irresponsible behavior and write down motivation for the changes

**Comment by Sammers21** [comment]
> Let's avoid this kind of irresponsible behavior and write down motivation for the changes

@olegmoz, description has been updated

**Comment by olegmoz** [comment]
@Sammers21 normally a problem that requires to be solved is described in an issue and PR description is about the way problem was solved. Also PR title is still non-informative and judgemental, I'd suggest to change it and avoid such wording in future

**Comment by Sammers21** [comment]
@olegmoz, better now?

**Comment by olegmoz** [comment]
@Sammers21 thanks, now the reason for is described. Though I do not understand what word `sign` is there for

File: src/main/java/com/artipie/asto/blocking/BlockingStorage.java [hunk 1]
```diff
@@ -43,30 +42,25 @@
     /**
      * Wrapped storage.
      */
-    private final Storage storage;
+    private final RxStorage storage;
```
Comment (olegmoz) [inline src/main/java/com/artipie/asto/blocking/BlockingStorage.java:45]: @Sammers21 could you please explain why we need to use `RxStorage` here? It will be way more simple to just keep using normal `Storage`, but to invoke `.join()` on it's results instead of `.get()`

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks, please see one comment

File: src/main/java/com/artipie/asto/blocking/BlockingStorage.java (hunk 1 above)
Comment (Sammers21) [reply src/main/java/com/artipie/asto/blocking/BlockingStorage.java:45]: @olegmoz, because `join` is a bad name for the operation. `CompletableFuture` in general is a badly-designed primitive for reactive programming and should be avoided where possible.

Comment (olegmoz) [reply src/main/java/com/artipie/asto/blocking/BlockingStorage.java:45]: @Sammers21 sorry, can't agree with you on `join` name being bad. It resembles "join thread" I believe. And `CompletableFuture` is not reactive programming primitive. Though it does not matter, neither `Storage` nor `BlockingStorage` are reactive and there is no sense to put something "reactive" in-between: it's unnecessary complication of code and waste of computation resources.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 please simplify `BlockingStorage` so it invokes `Storage` directly without wrapping it into `RxStorage`. Also it would be nice to remove unnecessary checked exception handling in all cases of `BlockingStorage` usage

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks, please remove emoji from commit message and fix the build - it is failing for some reason

**Comment by Sammers21** [comment]
> @Sammers21 thanks, please remove emoji from commit message and fix the build - it is failing for some reason

why should I remove the emoji?

**Comment by Sammers21** [comment]
@olegmoz, can we merge?

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/asto#280` is not assigned, can't get performer
